// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ges-runner")]
[assembly: AssemblyProductAttribute("Exira.EventStore.Runner")]
[assembly: AssemblyDescriptionAttribute("Exira.EventStore.Runner is a wrapper that uses Topshelf to run EventStore as a Windows Service")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyMetadataAttribute("githash","dbdde047cf8aef5f672843ffa02286a9c38f3bc1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
