// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ges-runner")]
[assembly: AssemblyProductAttribute("Exira.EventStore.Runner")]
[assembly: AssemblyDescriptionAttribute("Exira.EventStore.Runner is a wrapper that uses Topshelf to run EventStore as a Windows Service")]
[assembly: AssemblyVersionAttribute("0.1.3")]
[assembly: AssemblyFileVersionAttribute("0.1.3")]
[assembly: AssemblyMetadataAttribute("githash","47e38dd78e4164b7c6d7feeaa38933b46a4b24be")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.3";
    }
}
