// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ges-runner")]
[assembly: AssemblyProductAttribute("Exira.EventStore.Runner")]
[assembly: AssemblyDescriptionAttribute("Exira.EventStore.Runner is a wrapper that uses Topshelf to run EventStore as a Windows Service")]
[assembly: AssemblyVersionAttribute("0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1")]
[assembly: AssemblyMetadataAttribute("githash","d38ad61ff673ca34d69cb9e63b23de502372e70c")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1";
    }
}
